name: parte 2

on:
  push:
    branches-ignore:
      - main

jobs:
  parte2:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: descargar codigo
        uses: actions/checkout@v4

      - name: analizar codigo
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
