name: laboratorio8

on:
  push:
    branches-ignore:
      - main

jobs:
  laboratorio8:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Analizar código
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
